config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  # Root path
  root to: "pages#home"

  # Custom routes
  get '/dashboard', to: 'pages#dashboard'
  patch '/bookings/:id/accept', to: 'bookings#accept', as: 'accept'
  patch '/bookings/:id/decline', to: 'bookings#decline', as: 'decline'
  patch '/bookings/:id/return', to: 'bookings#return', as: 'return'

  get 'pages/profile/:id', to: 'pages#profile', as: 'profile_page'

  # Stone routes with nested bookings
  resources :stones do
    resources :bookings, only: [:new, :create, :show, :edit, :update]
  end

  resources :bookings

  # Health check route
  get "up", to: "rails/health#show", as: :rails_health_check
end

app/models/stone.rb
class Stone < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_one_attached :photo
  validates_presence_of :name
  has_many :bookings, dependent: :destroy

  include PgSearch::Model
  pg_search_scope :search_by_name_backstory_personnality,
  against: [ :name, :backstory, :personnality_traits ],
  associated_against: {
    category: [:name],
  },
  using: {
    tsearch: { prefix: true }
  }

  geocoded_by :address
  before_create :geocode

  private

  def address
    "#{user.city}, #{user.country}"
  end


end

app/controllers/stones_controller.rb
class StonesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  def index
    search
    set_markers(@stones)
  end

  def search
    @stones = Stone.all
      @stones = @stones.where(category_id: params[:category_id]) if params[:category_id].present?
      @stones = @stones.search_by_name_backstory_personnality(params[:query]) if params[:query].present?
      if params[:start_date].present? || params[:end_date].present?
      @stones = @stones.left_outer_joins(:bookings)
      # Exclure les pierres réservées pendant la période demandée
        if params[:start_date].present? && params[:end_date].present?
          @stones = @stones.where(
            'bookings.start_date >= ? OR bookings.end_date <= ? OR bookings.id IS NULL',
            params[:end_date], params[:start_date]
          )
        elsif params[:start_date].present?
          @stones = @stones.where(
            'bookings.start_date >= ? OR bookings.id IS NULL',
            params[:start_date]
          )
        elsif params[:end_date].present?
          @stones = @stones.where(
            'bookings.end_date <= ? OR bookings.id IS NULL',
            params[:end_date]
          )
        end
      end
  end

  def show
    @stone = Stone.find(params[:id])
    @booking = Booking.new
    @bookings = @stone.bookings
    @bookings_dates = @bookings.map do |booking|
      {
        from: booking.start_date,
        to:   booking.end_date
      }
    end
    set_marker(@stone)
  end

  def new
    @stone = Stone.new
  end

  def create
    @stone = Stone.new(stone_params)
    @stone.user = current_user
    if @stone.save!
      redirect_to @stone, notice: 'Stone was successfully created.'
    else
      render :new
    end
  end

    def edit
      @stone = Stone.find(params[:id])
    end

    def update
      @stone = Stone.find(params[:id])
      if @stone.update(stone_params)
        redirect_to @stone, notice: 'La pierre a été mise à jour avec succès.'
      else
        render :edit
      end
    end

    def destroy
      @stone = Stone.find(params[:id])
      if @stone.destroy
        redirect_to dashboard_path, notice: 'Une amie supprimée'
      else
        redirect_to dashboard_path, alert: 'Suppression impossible.'
      end
    end

  private

  def stone_params
    params.require(:stone).permit(:name, :size, :condition, :backstory, :daily_price, :personnality_traits, :photo, :category_id)
  end

  def set_markers(stones)
    @markers = stones.geocoded.map do |stone|
      {
        lat: stone.latitude,
        lng: stone.longitude
      }
    end
  end

  def set_marker(stone)
    if stone.latitude != nil && stone.longitude != nil
      @marker =[
        {
          lat: stone.latitude,
          lng: stone.longitude
        }
      ]
    else
      @marker = nil
    end
  end
end

app/views/stones/_search.html.erb
<div class="search-bar-container" data-controller="datepicker">
  <div class="d-none" data-datepicker-target="dateForm" data-bookings="<%= [].to_json %>"></div>
  <%= form_with url: stones_path, class:'search-bar-content', method: :get, local: true do |f| %>
      <!-- Barre de recherche -->
        <%= text_field_tag :query,
              params[:query],
              placeholder: "Entrez un mot clé",
              class: "search-input"%>

      <%= f.select :category_id,
          options_from_collection_for_select(Category.all, :id, :name, params[:category_id]),
          { include_blank: "Toutes les catégories" },
          class: "category-select" %>

        <!-- Bouton pour afficher/masquer le calendrier -->
        <button type="button",
                class="rounded-button secondary",
                data-action="click->datepicker#toggleCalendar">
          📅 Choisir une date
        </button>

      <!-- Champs de date masqués -->
      <div id="datepicker-container"
         class="datepicker-container hidden"
         data-datepicker-target="datepickerContainer">

        <!-- Champ Date de début -->
        <%= f.label :start_date, class: "d-none", for: "range_start" %>
        <%= f.text_field :start_date,
                required: false,
                id: "range_start",
                class: "d-none",
                data: { datepicker_target: "start", booking_target: "startDate" } %>

        <!-- Champ Date de fin -->
        <%= f.label :end_date, class: "d-none", for: "range_end" %>
        <%= f.text_field :end_date,
                        required: false,
                        id: "range_end",
                        class: "d-none",
                        data: { datepicker_target: "end", booking_target: "endDate" } %>
      </div>

    <!-- Bouton rechercher -->
      <button type="submit" class="rounded-button primary">Rechercher</button>
    <% end %>
  </div>

app/views/stones/create.html.erb
<h1>Stones#create</h1>
<p>Find me in app/views/stones/create.html.erb</p>

app/views/stones/destroy.html.erb
<h1>Stones#destroy</h1>
<p>Find me in app/views/stones/destroy.html.erb</p>

app/views/stones/edit.html.erb
 <div class="container">
  <div class="form-container">
        <h1>Modifier votre pierre</h1>


      <%# Start form %>
          <%= simple_form_for(@stone) do |f| %>
            <%= f.input :name, label: "Le nom de votre pierre" %>
            <%= f.input :size, as: :select, label: "Sa taille", collection:
                ['Quelques grammes', 'Quelques kilos', 'Quelques tonnes'], include_blank: "Sélectionnez une taille" %>
                <%= f.input :condition, as: :select, label: "État de la pierre", collection:
                ["Neuve de quelques millions d'années", "Moyennement neuve du temps d'avant les dinosaures", "Naissance de la terre"],
                include_blank: "Sélectionnez une taille" %>
            <%= f.input :personnality_traits, label: "Sa personnalité" %>
            <%= f.input :backstory, as: :text, label: "Son histoire", input_html: { rows: 5, class: 'form-control' } %>
            <%= f.association :category, label: "Categorie" %>
            <%= f.input :daily_price, label: "À quel prix souhaitez-vous la proposer ? (€ / jour)" %>

        <%# Start if de la photo actuelle %>
            <% if @stone.photo.attached? %>
              <p>Photo actuelle :</p>
              <%= cl_image_tag @stone.photo.key, height: 100 %>
            <%= f.submit "Enregistrer les modifications", class: "rounded-button primary" %>
            <% end %>
        <%# If end %>


      <%# End du form %>
            <% end %>
  </div>
</div>

app/views/stones/index.html.erb
<div class="container">
<%= render 'search' %>

<div class="results-container">
  <div class="cards-stone">
    <% @stones.each do |stone| %>
<%= link_to stone_path(stone), class: "card-link" do %>
        <div class="card-stone">
          <div>
          <% if stone.photo.attached? %>
            <%= cl_image_tag stone.photo.key %>
          <% end %>
          </div>
          <div class="card-body">
            <div class="card-description">
              <p class="card-category"><%= stone.category.name %></p>
              <h5 class="card-name"><%= stone.name %></h5>
              <% if stone.user == current_user %>
              <p class=card-backstory>(votre pierre) <%= truncate(stone.backstory, length: 80, separator: ' ', omission: '...') %></p>
              <% else %>
              <p class="card-backstory"><%= truncate(stone.backstory, length: 80, separator: ' ', omission: '...') %></p>
              <% end %>
            </div>
            <div class="price">
              <p class="card-daily-price"><%= stone.daily_price %>€ par jour</p>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
    </div>

    <div class="map-stone border border-2 ms-4">
      <div style="width: 100%; height: 100%;"
        data-controller="map"
        data-map-markers-value="<%= @markers.to_json %>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
  </div>
</div>

app/views/stones/new.html.erb
<div class="container">
  <h1 class="mt-3">Ajouter une pierre a votre collection</h1>
      <div class="form-container">
          <%= simple_form_for(@stone) do |f| %>
            <%= f.input :name, label: "Le nom de votre pierre" %>
             <%= f.input :size, as: :select, label: "Sa taille", collection:
                ['Quelques grammes', 'Quelques kilos', 'Quelques tonnes'], include_blank: "Sélectionnez une taille" %>
                <%= f.input :condition, as: :select, label: "État de la pierre", collection:
                ["Immaculée", "Toute neuve", "Un peu frottée", "Éraflée d’aventures", "Craquelée mais vaillante", "Mousseuse et zen"],
                include_blank: "Sélectionnez un état" %>
            <%= f.input :personnality_traits, label: "Sa personnalité" %>
            <%= f.input :backstory, as: :text, label: "Son histoire", input_html: { rows: 5, class: 'form-control' } %>
            <%= f.association :category, label: "Categorie" %>
            <%= f.input :daily_price, label: "À quel prix souhaitez-vous la proposer ? (€ / jour)" %>
            <%= f.input :photo, as: :file, label: "Photo" %>
            <%= f.submit "Enregistrer", class:"rounded-button primary"%>
          <% end %>
    </div>
</div>

app/views/stones/show.html.erb
<div class="container">


<div class="show-big-container", data-controller="datepicker">
  <div class="show-container">
    <div class="left-stone-container">
      <div>
        <div class="align-center">
          <% if @stone.photo.attached? %>
            <%= cl_image_tag @stone.photo.key, class: "stone-show-card-img" %>
          <% else %>
            <%= cl_image_tag "development/17n6kwpi22xr4dlapk6w6t56qudu", class: "stone-show-card-img", alt: "Image par défaut" %>
          <% end %>
        </div>

          <div>
            <% if @stone.user == current_user %>
              <div class="d-flex align-items-center justify-content-end"> <!-- justify-content-end pour aligner à droite -->
                <div class="icon-wrapper" style="margin-right: 16px;"> <!-- marge pour espacer les icônes -->
                  <%= link_to edit_stone_path(@stone) do %>
                    <i class="fa-regular fa-pen-to-square" style="width: 30px; color: black;"></i>
                  <% end %>
                </div>
                <div class="icon-wrapper">
                  <%= link_to stone_path(@stone), data: { turbo_method: :delete, turbo_confirm: 'Vous voulez vraiment supprimer cette pierre ?' } do %>
                    <i class="fa-solid fa-xmark" style="width: 30px; color: black;"></i>
                  <% end %>
                </div>
              </div>
            <% end %>
          </div>
          <div>
            <h1>Découvrez <strong><%= @stone.name %></strong></h1>
            <h4><%= @stone.category.name %> : <%= @stone.category.properties %> </h4>
            <p>Son histoire : <%= @stone.backstory %></p>
          </div>
        </div>
        <div class="show-mail">
          <h2>L'heureux propriétaire</h2>
          <p><%= @stone.user.first_name %> possède <%= @stone.user.stones.count %> pierres</p>
      </div>
    </div>

    <div class="right-stone-container">
        <% if @marker != nil %>
        <h2>Localisation</h2>
          <div class="map-stone-show">
              <div style="width: 100%; height: 100%;"
                data-controller="map"
                data-map-markers-value="<%= @marker.to_json %>"
                data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
              </div>
            </div>
          <% end %>

            <% if @stone.user == current_user %>
              <div>
                <h2>Bookings de cette pierre : </h2>
                <ul class="list-group">
                  <% @stone.bookings.each do |booking| %>
                    <li class="d-flex justify-content-between align-items-center py-2"> <!-- Ajout de padding vertical -->
                      <%= link_to dashboard_path, class: "text-decoration-none d-flex justify-content-between align-items-center w-100" do %>
                        <div class="d-flex flex-column text-dark"> <!-- Conteneur pour le texte -->
                          <p class="mb-1">Réservation par <%= booking.user.first_name %> du <%= booking.start_date %> au <%= booking.end_date %></p>
                        </div>
                        <p class="status-booking mb-0 text-dark" style="margin-left: 16px;"><%= booking.status %></p> <!-- Espacement horizontal -->
                      <% end %>
                    </li>
                  <% end %>
                </ul>
              </div>
            <% end %>

        <% unless @stone.user == current_user %>
        <h2>Réservation</h2>
        <div class="cal-stone-show">
        <div class="form-wrapper"
            data-controller="booking"
            data-booking-start-date-value="<%= params[:start_date] %>"
            data-booking-end-date-value="<%= params[:end_date] %>"
            data-booking-price-value="<%= Stone.find(params[:id]).daily_price %>">
          <div id="price">
            <h3 data-booking-target="priceShow"></h3>
          </div>

           <div data-action="change->booking#updatePrice">
            <%= simple_form_for [@stone, @booking] do |f| %>
              <%= f.input :start_date, as: :string,
                                      required: false,
                                      label: false,
                                      input_html: { class: "d-none", id: "range_start", data: { datepicker_target: "start", booking_target: "startDate" } } %>
              <%= f.input :end_date, as: :string,
                                    required: false,
                                    label: false,
                                    input_html: { class: "d-none", id: "range_end", data: { datepicker_target: "end", booking_target: "endDate" } } %>
              <%= f.button :submit, "Réserver cette pierre", class: "rounded-button primary" %>
            <% end %>
          </div>
        <% end %>

        <div data-datepicker-target="dateForm"
             data-bookings="<%= @bookings_dates.to_json %>">
        </div>
    </div>
    </div>
  </div>


</div>
</div>
</div>

app/views/stones/update.html.erb
<h1>Stones#update</h1>
<p>Find me in app/views/stones/update.html.erb</p>