config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  # Root path
  root to: "pages#home"

  # Custom routes
  get '/dashboard', to: 'pages#dashboard'
  patch '/bookings/:id/accept', to: 'bookings#accept', as: 'accept'
  patch '/bookings/:id/decline', to: 'bookings#decline', as: 'decline'
  patch '/bookings/:id/return', to: 'bookings#return', as: 'return'

  get 'pages/profile/:id', to: 'pages#profile', as: 'profile_page'

  # Stone routes with nested bookings
  resources :stones do
    resources :bookings, only: [:new, :create, :show, :edit, :update]
  end

  resources :bookings

  # Health check route
  get "up", to: "rails/health#show", as: :rails_health_check
end

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon" data-controller="navbar">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
     <h1>StoneEdge</h1>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <% if current_user.avatar.attached? %>
            <%= image_tag current_user.avatar.variant(resize_to_fill: [50, 50]), alt: "Profile Picture", class: "profile-picture" %>
          <% else %>
            <%= image_tag "default_profile.png", alt: "Default Profile", class: "profile-picture", width: 50, height: 50 %>
          <% end %>
          </a>

            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
             <%= link_to "/dashboard", class: "dropdown-item" do %>
              <p class="dropdown-item-custom"><i class="fa-solid fa-gauge"></i> Dashboard</p>
              <% end %>
             <%= link_to profile_page_path(id: current_user.id), class: "dropdown-item" do %>
              <p class="dropdown-item-custom"><i class="fa-solid fa-user"></i> Mon profil</p>
              <% end %>
             <%= link_to  destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" do %>
             <p class="dropdown-item-custom"><i class="fa-solid fa-arrow-right-from-bracket"></i> Déconnexion</p>
             <% end %>
            </div>
          </li>
        <% else %>
         <li class="nav-item">
          <%= link_to new_user_session_path, class: "nav-link" do %>
            <i class="fa-solid fa-user"></i> Login
          <% end %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>
<div class="back-results" style="<%= 'display: none;' if controller_name == 'pages' && action_name == 'home' %>">
  <%= link_to "<< Back", :back %>
</div>